[package]
name = "rust_todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19.0"
crossterm = "0.27"
rusqlite = { version = "0.31.0", features = ["bundled"] }
unicode-width = "0.1"
